swagger: "2.0"
info:
  description: "Description"
  version: "1.0.0"
  title: "BehaviorWatcher"
  termsOfService: "http://swagger.io/terms/"
schemes:
  - "https"
  - "http"
basePath: "/api"

paths:
  /metrics:
    get:
      operationId: api.metrics.read_all
      summary: List all metrics
      description: List all metrics
      tags:
        - Metric
      produces:
        - application/json
      parameters:
        - name: userId
          in: query
          type: integer
        - name: taskId
          in: query
          type: integer
      responses:
        '200':
          description: Successfully read metrics
          schema:
            type: array
            items:
              $ref: "#/definitions/MetricModel"
        '400':
          description: Bad request. If some data are strange
          schema:
            $ref: "#/definitions/Error"
        '500':
          description: Unexpected error.
          schema:
            $ref: "#/definitions/Error"

    post:
      operationId: api.metrics.create
      summary: Create new metric in system.
      description: Create new metric in system.
      tags:
        - Metric
      produces:
        - application/json
      parameters:
        - name: metric
          in: body
          required: true
          description: ''
          schema:
            $ref: '#/definitions/CreateMetricModel'
      responses:
        '201':
          description: Successfully read metric
          schema:
            $ref: '#/definitions/MetricModel'
        '400':
          description: Bad request
          schema:
            $ref: '#/definitions/MetricModel'
        '409':
          description: Specified metric already exists
          schema:
            $ref: '#/definitions/Error'
        '500':
          description: Unexpected error.
          schema:
            $ref: '#/definitions/Error'

  /metrics/{metricId}:
    get:
      operationId: api.metrics.read_one
      description: Get concrete metric by id
      tags:
        - Metric
      produces:
        - application/json
      parameters:
      - name: metricId
        in: path
        required: true
        type: string
      responses:
        '200':
          description: Successfully read metric
          schema:
            $ref: '#/definitions/MetricModel'
        '400':
          description: Bad request. If some data are strange
          schema:
            $ref: '#/definitions/Error'
        '404':
          description: Not found
          schema:
            $ref: '#/definitions/Error'
        '500':
          description: Unexpected error.
          schema:
            $ref: '#/definitions/Error'

definitions:
  MetricModel:
    type: "object"
    properties:
      id:
        type: "integer"
      userId:
        type: "integer"
      taskId:
        type: "integer"
      taskCopied:
        type: "boolean"
      taskViewed:
        type: "boolean"
      readingTime:
        type: "integer"

  Error:
    title: Error message
    type: object
    properties:
      message:
        type: string
    required:
      - message

  CreateMetricModel:
    type: "object"
    properties:
      userId:
        type: "integer"
      taskId:
        type: "integer"
      taskCopied:
        type: "boolean"
        default: false
      taskViewed:
        type: "boolean"
        default: false
      readingTime:
        type: "integer"
    required:
      - userId
      - taskId
        