swagger: "2.0"
info:
  description: "Description"
  version: "1.0.0"
  title: "BehaviorWatcher"
  termsOfService: "http://swagger.io/terms/"
schemes:
  - "https"
  - "http"
basePath: "/api"

paths:
  /metrics:
    get:
      operationId: api.metrics.read_all
      tags:
        - Metric
      produces:
        - application/json
      parameters:
        - name: userId
          in: query
          required: False
          type: integer
        - name: taskId
          in: query
          required: False
          type: integer
      summary: List all metrics
      description: List all metrics
      responses:
        "200":
          description: Successfully read metrics
          schema:
            type: array
            items:
              $ref: "#/definitions/MetricModel"
        "400":
          description: Bad request. If some data are strange
          schema:
            $ref: "#/definitions/Error"
        "500":
          description: Unexpected error.
          schema:
            $ref: "#/definitions/Error"

    post:
      description: Create new metric in system.
      tags:
        - Metric
      produces:
      - application/json
      parameters:
      - name: Body
        in: body
        required: true
        description: ''
        schema:
          $ref: '#/definitions/CreateMetricModel'
      responses:
        '200':
          description: OK.
          schema:
            $ref: '#/definitions/MetricModel'
        '400':
          description: Bad request. If some data are strange
          schema:
            $ref: '#/definitions/Error'
        '500':
          description: Unexpected error.
          schema:
            $ref: '#/definitions/Error'
definitions:
  MetricModel:
    type: "object"
    properties:
      id:
        type: "integer"
      userId:
        type: "integer"
      taskId:
        type: "integer"
      taskCopied:
        type: "boolean"
      taskViewed:
        type: "boolean"
      readingTime:
        type: "integer"

  Error:
    title: Error message
    type: object
    properties:
      message:
        type: string
    required:
      - message
