version: "3"

services:
  backend:
    build: backend
    ports:
      - "5000:5000"
    restart: "always"
    # TODO: add volume for persistence

  frontend:
    build: frontend
    environment:
      - APPLICATION_HOST=0.0.0.0
    ports:
      - "8080:8080"
    restart: "always"
