swagger: "2.0"
info:
  description: "Description"
  version: "1.0.0"
  title: "BehaviorWatcher"
  termsOfService: "http://swagger.io/terms/"
host: "example.com"
basePath: "/path"
schemes:
- "https"
- "http"
paths:
  /metrics:
    get:
      description: List of all metrics in system.
      tags:
        - Metric
      produces:
        - application/json
      parameters:
      - name: userId
        in: query
        type: integer
      - name: taskId
        in: query
        type: integer
      responses:
        '200':
          description: OK.
          schema:
            type: array
            items:
              $ref: '#/definitions/MetricModel'
        '400':
          description: Bad request. If some data are strange
          schema:
            $ref: '#/definitions/Error'
        '500':
          description: Unexpected error.
          schema:
            $ref: '#/definitions/Error'
    post:
      description: Create new metric in system.
      tags:
        - Metric
      produces:
      - application/json
      parameters:
      - name: Body
        in: body
        required: true
        description: ''
        schema:
          $ref: '#/definitions/CreateMetricModel'
      responses:
        '200':
          description: OK.
          schema:
            $ref: '#/definitions/MetricModel'
        '400':
          description: Bad request. If some data are strange
          schema:
            $ref: '#/definitions/Error'
        '500':
          description: Unexpected error.
          schema:
            $ref: '#/definitions/Error'

  /metrics/{metricId}:
    get:
      description: Get concrete metric in system
      tags:
        - Metric
      produces:
        - application/json
      parameters:
      - name: metricId
        in: path
        required: true
        type: string
      responses:
        '200':
          description: OK.
          schema:
            $ref: '#/definitions/MetricModel'
        '400':
          description: Bad request. If some data are strange
          schema:
            $ref: '#/definitions/Error'
        '500':
          description: Unexpected error.
          schema:
            $ref: '#/definitions/Error'
    patch:
      description: Edit data for concrete metric
      tags:
        - Metric
      produces:
      - application/json
      parameters:
      - name: metricId
        in: path
        required: true
        type: string
      - name: Body
        in: body
        required: true
        description: ''
        schema:
          $ref: '#/definitions/EditMetricModel'
      responses:
        '200':
          description: OK.
          schema:
            $ref: '#/definitions/MetricModel'
        '400':
          description: Bad request. If some data are strange
          schema:
            $ref: '#/definitions/Error'
        '500':
          description: Unexpected error.
          schema:
            $ref: '#/definitions/Error'
    delete:
      description: Delete concrete metric
      tags:
        - Metric
      produces:
      - application/json
      parameters:
      - name: metricId
        in: path
        required: true
        type: string
      responses:
        '200':
          description: OK.
          schema:
            type: object
            properties:
              message: 
                type: string
                example: 'OK'
        '400':
          description: Bad request. If some data are strange
          schema:
            $ref: '#/definitions/Error'
        '500':
          description: Unexpected error.
          schema:
            $ref: '#/definitions/Error'
  
  /metrics/{metricId}/receivers:
    get:
      description: List of receivers of current metric.
      tags:
        - Receiver
      produces:
      - application/json
      parameters:
      - name: metricId
        in: path
        required: true
        type: integer
        description: ''
      responses:
        '200':
          description: OK.
          schema:
            type: array
            items:
              $ref: '#/definitions/ReceiverModel'
        '400':
          description: Bad request. If some data are strange
          schema:
            $ref: '#/definitions/Error'
        '500':
          description: Unexpected error.
          schema:
            $ref: '#/definitions/Error'
    post:
      description: Add receivers to current metric
      tags:
      - Receiver
      produces:
      - application/json
      parameters:
      - name: metricId
        in: path
        required: true
        type: integer
      - name: Body
        in: body
        required: true
        schema:
          type: array
          items:
            type: integer
          example: [2, 7]
      responses:
        '200':
          description: OK.
          schema:
            type: array
            items:
              $ref: '#/definitions/MetricExtendedModel'
        '400':
          description: Bad request. If some data are strange
          schema:
            $ref: '#/definitions/Error'
        '500':
          description: Unexpected error.
          schema:
            $ref: '#/definitions/Error'
  
  /receivers/{receiverId}:
    get:
      description: Get concrete receiver in system
      tags:
        - Receiver
      produces:
      - application/json
      parameters:
      - name: receiverId
        in: path
        required: true
        type: integer
      responses:
        '200':
          description: OK.
          schema:
            type: array
            items:
              $ref: '#/definitions/ReceiverModel'
        '400':
          description: Bad request. If some data are strange
          schema:
            $ref: '#/definitions/Error'
        '500':
          description: Unexpected error.
          schema:
            $ref: '#/definitions/Error'
    delete:
      description: Delete concrete receiver
      tags:
        - Receiver
      produces:
      - application/json
      parameters:
      - name: receiverId
        in: path
        required: true
        type: string
        description: ''
      responses:
        '200':
          description: OK.
          schema:
            type: object
            properties:
              message: 
                type: string
                example: 'OK'
        '400':
          description: Bad request. If some data are strange
          schema:
            $ref: '#/definitions/Error'
        '500':
          description: Unexpected error.
          schema:
            $ref: '#/definitions/Error'     
  
  /metrics/{metricId}/senders:
    get:
      description: List of senders of current metric.
      tags:
        - Sender
      produces:
      - application/json
      parameters:
      - name: metricId
        in: path
        required: true
        type: integer
        description: ''
      responses:
        '200':
          description: OK.
          schema:
            type: array
            items:
              $ref: '#/definitions/SenderModel'
        '400':
          description: Bad request. If some data are strange
          schema:
            $ref: '#/definitions/Error'
        '500':
          description: Unexpected error.
          schema:
            $ref: '#/definitions/Error'
    post:
      description: Add senders to current metric
      tags:
      - Sender
      produces:
      - application/json
      parameters:
      - name: metricId
        in: path
        required: true
        type: integer
      - name: Body
        in: body
        required: true
        schema:
          type: array
          items:
            type: integer
          example: [2, 7]
      responses:
        '200':
          description: OK.
          schema:
            type: array
            items:
              $ref: '#/definitions/MetricExtendedModel'
        '400':
          description: Bad request. If some data are strange
          schema:
            $ref: '#/definitions/Error'
        '500':
          description: Unexpected error.
          schema:
            $ref: '#/definitions/Error'
  
  /senders/{senderId}:
    get:
      description: Get concrete sender in system
      tags:
        - Sender
      produces:
      - application/json
      parameters:
      - name: senderId
        in: path
        required: true
        type: integer
      responses:
        '200':
          description: OK.
          schema:
            type: array
            items:
              $ref: '#/definitions/SenderModel'
        '400':
          description: Bad request. If some data are strange
          schema:
            $ref: '#/definitions/Error'
        '500':
          description: Unexpected error.
          schema:
            $ref: '#/definitions/Error'
    delete:
      description: Delete concrete sender
      tags:
        - Sender
      produces:
      - application/json
      parameters:
      - name: senderId
        in: path
        required: true
        type: string
        description: ''
      responses:
        '200':
          description: OK.
          schema:
            type: object
            properties:
              message: 
                type: string
                example: 'OK'
        '400':
          description: Bad request. If some data are strange
          schema:
            $ref: '#/definitions/Error'
        '500':
          description: Unexpected error.
          schema:
            $ref: '#/definitions/Error'     
            
definitions:
  MetricModel:
    type: "object"
    properties:
      id:
        type: "integer"
      userId:
        type: "integer"
      taskId:
        type: "integer"
      taskCopied:
        type: "boolean"
      taskViewed:
        type: "boolean"
      readingTime:
        type: "integer"
  
  MetricExtendedModel:
    type: "object"
    properties:
      id:
        type: "integer"
      userId:
        type: "integer"
      taskId:
        type: "integer"
      taskCopied:
        type: "boolean"
      taskViewed:
        type: "boolean"
      readingTime:
        type: "integer"
      receivers:
        type: array
        items:
          $ref: '#/definitions/ReceiverModel'
      senders:
        type: array
        items:
          $ref: '#/definitions/SenderModel'
      
  CreateMetricModel:
    type: "object"
    properties:
      userId:
        type: "integer"
      taskId:
        type: "integer"
      taskCopied:
        type: "boolean"
        default: false
      taskViewed:
        type: "boolean"
        default: false
      readingTime:
        type: "integer"
    required:
      - usedId
      - taskId
        
  EditMetricModel:
    type: "object"
    properties:
      userId:
        type: "integer"
      taskId:
        type: "integer"
      taskCopied:
        type: "boolean"
      taskViewed:
        type: "boolean"
      readingTime:
        type: "integer"
        
  ReceiverModel:
    type: "object"
    properties:
      metricId:
        type: "integer"
        example: 2
      userId:
        type: "integer"
        example: 7
    required:
      - userId
      - metricId
    
  SenderModel:
    type: "object"
    properties:
      metricId:
        type: "integer"
        example: 13
      userId:
        type: "integer"
        example: 9
    required:
      - userId
      - metricId

  Error:
    title: Error message
    type: object
    properties:
      message:
        type: string
    required:
      - message