swagger: "2.0"
info:
  description: "Description"
  version: "1.0.0"
  title: "BehaviorWatcher"
  termsOfService: "http://swagger.io/terms/"
host: "example.com"
basePath: "/path"
schemes:
- "https"
- "http"
paths:
  /metric:
    post:
      tags:
      - "pet"
      summary: "Add a new pet to the store"
      description: ""
      operationId: "addPet"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Pet object that needs to be added to the store"
        required: true
        schema:
          $ref: "#/definitions/Metric"
      responses:
        "405":
          description: "Invalid input"
    patch:
      tags:
      - "pet"
      summary: "Update an existing pet"
      description: ""
      operationId: "updatePet"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Pet object that needs to be added to the store"
        required: true
        schema:
          $ref: "#/definitions/Metric"
      responses:
        "400":
          description: "Invalid ID supplied"
          schema:
            $ref: "#/definitions/Metric"
        "404":
          description: "Pet not found"
        "405":
          description: "Validation exception"
definitions:
  Metric:
    type: "object"
    properties:
      userId:
        type: "integer"
      taskId:
        type: "integer"
      shipDate:
        type: "string"
        format: "date-time"
      status:
        type: "string"
        description: "Order Status"
        enum:
        - "placed"
        - "approved"
        - "delivered"
      complete:
        type: "boolean"
        default: false
    xml:
      name: "Order"
externalDocs:
  description: "Find out more about Swagger"
  url: "http://swagger.io"